@startuml

abstract class NamedElement {
 + String name
}

class App

class Actuator {
  + int pin
}

class State {
 + transitions
}

class Action {
  + SIGNAL value
}

class Transition {
  + contitions
  + next
}

class Sensor {
 + signal
}

enum SIGNAL {
    HIGH
    LOW
}


NamedElement <|-- App
NamedElement <|-- Actuator
NamedElement <|-- State

App *--> "1..*\nstates" State
State *--> Transition
Transition --> "Next" State
Transition --> "Conditions" Sensor
App *--> "1..*\nactuators" Actuator
State *--> "1..*\nactions" Action
Action --> "1 target" Actuator

@enduml